jms_security_extra:
    secure_all_services: false
    expressions: true

security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext
        Dev\AeroportBundle\Entity\Internaute: plaintext
        

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        main_provider:
            entity: { class: Dev\AeroportBundle\Entity\Internaute, property: email }

    firewalls:
        main:
            pattern: ^/
            anonymous: true
            provider: main_provider
            form_login:
                login_path: security_login
                check_path: security_logincheck
            logout:
                path: security_logout
                target: homepage
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false
            #anonymous: ~
            #http_basic:
            #    realm: "Secured Demo Area"
            
        
        
        
    access_control:
        #- { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/client, roles: ROLE_USER }
        
        #
        # You must uncomment the two following rules to restrict access to paths
        # starting with the /_internal prefix to only localhost
        #- { path: ^/_internal/secure, roles: IS_AUTHENTICATED_ANONYMOUSLY, ip: 127.0.0.1 }
        #- { path: ^/_internal/secure, roles: ROLE_NO_ACCESS }
