<?php

namespace Dev\AeroportBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * AvionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AvionRepository extends EntityRepository
{
}
