<?php

namespace Dev\AeroportBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CompagnieRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CompagnieRepository extends EntityRepository
{
}
