<?php

namespace Dev\AeroportBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ReserveRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReserveRepository extends EntityRepository
{
    
    
    public function getReservationsClient($cliId)
    {
        return $this->getEntityManager()
            ->createQuery('SELECT v
                FROM DevAeroportBundle:Reserve r, DevAeroportBundle:Vol v
                WHERE r.volId = v.volId AND r.cliId = '.$cliId)
            ->getResult();
    }
    
    
    public function removeReservation($volId, $cliId)
    {
        return $this->getEntityManager()
            ->createQuery('DELETE
                FROM DevAeroportBundle:Reserve r
                WHERE r.volId = '.$volId.' AND r.cliId = '.$cliId)
            ->getResult();
    }
    
    
    
    
    
}
