<?php

namespace Dev\AeroportBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * VolRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VolRepository extends EntityRepository
{
    
    
    public function getReservationsVol($volId)
    {
        return $this->getEntityManager()
            ->createQuery('SELECT i
                FROM DevAeroportBundle:Internaute i, DevAeroportBundle:Reserve r, DevAeroportBundle:Vol v
                WHERE i.id = r.cliId AND r.volId = v.volId AND v.volId = '.$volId)
            ->getResult();
    }
    
    
}
